trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y dos2unix
    sudo apt-get install -y perl
    sudo apt-get install -y libdbd-pg-perl libdbi-perl libipc-run-perl

    echo "Configuring CPAN non-interactively"
    PERL_MM_USE_DEFAULT=1 cpan App::cpanminus
    cpanm --notest Log::Log4perl
    cpanm --notest Sort::Naturally

    wget https://raw.githubusercontent.com/dalibo/sqlserver2pgsql/master/sqlserver2pgsql.pl
    chmod +x sqlserver2pgsql.pl
  displayName: 'Install dependencies and sqlserver2pgsql'

- script: |
    echo "Listing files in $(Build.SourcesDirectory)/src/HNG.Database/Schemas"
    ls -la $(Build.SourcesDirectory)/src/HNG.Database/Schemas
    echo "Listing files in $(Build.SourcesDirectory)/src/HNG.Database/Scripts"
    ls -la $(Build.SourcesDirectory)/src/HNG.Database/Scripts
  displayName: 'List files in subdirectories'

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/postgres-scripts
    for file in $(find $(Build.SourcesDirectory)/src/HNG.Database -name "*.sql"); do
      echo "Processing $file"
      dos2unix $file
      ./sqlserver2pgsql.pl -f $file -b $(Build.ArtifactStagingDirectory)/postgres-scripts/$(basename $file .sql)_pg.sql
      if [ $? -ne 0 ]; then
        echo "Error processing $file"
        exit 1
      fi
    done
  displayName: 'Convert SQL Server scripts to PostgreSQL'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/postgres-scripts'
    ArtifactName: 'postgres-scripts'
